import type { Dictionary } from "@textguard/core";

export const faProfanity: Dictionary = {
  name: "fa-profanity",
  language: "fa",
  version: "1.0.0",
  words: [
    // === کلمات رکیک ۳ حرفی و ریشه‌ای (اولویت بالا در پردازش) ===
    { word: "کیر", severity: "high", category: "profanity" },
    { word: "کیرر", severity: "high", category: "profanity" },
    { word: "کس", severity: "high", category: "profanity" },
    { word: "کص", severity: "high", category: "profanity" },
    { word: "کوص", severity: "high", category: "profanity" },
    { word: "کوس", severity: "high", category: "profanity" },
    { word: "کث", severity: "high", category: "profanity" },
    { word: "کون", severity: "high", category: "profanity" },
    { word: "کونن", severity: "high", category: "profanity" },
    { word: "خایه", severity: "high", category: "profanity" },
    { word: "ممه", severity: "high", category: "profanity" },
    { word: "دول", severity: "high", category: "profanity" },
    { word: "اوب", severity: "high", category: "profanity" },
    { word: "اوبی", severity: "high", category: "profanity" },
    { word: "لز", severity: "high", category: "profanity" },
    { word: "جکس", severity: "high", category: "profanity" },

    // === اصطلاحات جنسی، پورنوگرافی و فواحش ===
    { word: "سکس", severity: "high", category: "profanity" },
    { word: "سکسی", severity: "high", category: "profanity" },
    { word: "سسکی", severity: "high", category: "profanity" },
    { word: "سکسیی", severity: "high", category: "profanity" },
    { word: "سکسیم", severity: "high", category: "profanity" },
    { word: "پورن", severity: "high", category: "profanity" },
    { word: "فیلم سوپر", severity: "high", category: "profanity" },
    { word: "فاحشه", severity: "high", category: "profanity" },
    { word: "فاحشه خانم", severity: "high", category: "profanity" },
    { word: "جنده", severity: "high", category: "profanity" },
    { word: "خانم جنده", severity: "high", category: "profanity" },
    { word: "جنده پولی", severity: "high", category: "profanity" },
    { word: "جنده خانه", severity: "high", category: "profanity" },
    { word: "صیغه ای", severity: "high", category: "profanity" },
    { word: "هرزه", severity: "high", category: "profanity" },
    { word: "بکارت", severity: "high", category: "profanity" },
    { word: "ارگاسم", severity: "high", category: "profanity" },
    { word: "پریود", severity: "medium", category: "profanity" },
    { word: "مغز پریودی", severity: "high", category: "profanity" },

    // === ترکیب‌های توهین‌آمیز جنسی و افعال گاییدن ===
    { word: "گایدن", severity: "high", category: "profanity" },
    { word: "گاییدن", severity: "high", category: "profanity" },
    { word: "گایدی", severity: "high", category: "profanity" },
    { word: "بکنمت", severity: "high", category: "profanity" },
    { word: "بکن", severity: "high", category: "profanity" },
    { word: "بکن توش", severity: "high", category: "profanity" },
    { word: "بکنش", severity: "high", category: "profanity" },
    { word: "بکن بکن", severity: "high", category: "profanity" },
    { word: "کردن", severity: "high", category: "profanity" },
    { word: "کردنی", severity: "high", category: "profanity" },
    { word: "دهن گاییده", severity: "high", category: "profanity" },
    { word: "دهنتو گاییدم", severity: "high", category: "profanity" },
    { word: "بمال", severity: "high", category: "profanity" },
    { word: "مالوندن", severity: "high", category: "profanity" },
    { word: "حشری", severity: "high", category: "profanity" },
    { word: "حشری شدن", severity: "high", category: "profanity" },
    { word: "حشر", severity: "high", category: "profanity" },
    { word: "شهوتی", severity: "high", category: "profanity" },
    { word: "شق کردن", severity: "high", category: "profanity" },
    { word: "فرو کن", severity: "high", category: "profanity" },
    { word: "چرب کنش", severity: "high", category: "profanity" },

    // === مشتقات کلمات کیر و کس و کوس ===
    { word: "کیری", severity: "high", category: "profanity" },
    { word: "سرکیر", severity: "high", category: "profanity" },
    { word: "آب کیر", severity: "high", category: "profanity" },
    { word: "کله کیری", severity: "high", category: "profanity" },
    { word: "کیرناز", severity: "high", category: "profanity" },
    { word: "کیردراز", severity: "high", category: "profanity" },
    { word: "کیردوس", severity: "high", category: "profanity" },
    { word: "کیر خر", severity: "high", category: "profanity" },
    { word: "کیرمکیدن", severity: "high", category: "profanity" },
    { word: "کیروکس", severity: "high", category: "profanity" },
    { word: "کس و کیر", severity: "high", category: "profanity" },
    { word: "کسشعر", severity: "high", category: "profanity" },
    { word: "کس کردن", severity: "high", category: "profanity" },
    { word: "کس دادن", severity: "high", category: "profanity" },
    { word: "کس لیسیدن", severity: "high", category: "profanity" },
    { word: "کس خیس", severity: "high", category: "profanity" },
    { word: "کس خور", severity: "high", category: "profanity" },
    { word: "کس لیس", severity: "high", category: "profanity" },
    { word: "کص لیس", severity: "high", category: "profanity" },
    { word: "کث لیس", severity: "high", category: "profanity" },
    { word: "کوص لیس", severity: "high", category: "profanity" },
    { word: "کوث لیس", severity: "high", category: "profanity" },
    { word: "کوس لیس", severity: "high", category: "profanity" },
    { word: "کوس خور", severity: "high", category: "profanity" },
    { word: "کصکلک بازی", severity: "high", category: "profanity" },
    { word: "کسپولی", severity: "high", category: "profanity" },
    { word: "کصپولی", severity: "high", category: "profanity" },
    { word: "خارکونی", severity: "high", category: "profanity" },
    { word: "خارکیونی", severity: "high", category: "profanity" },

    // === مشتقات کون، باسن و آناتومی جنسی ===
    { word: "کونده", severity: "high", category: "profanity" },
    { word: "کون ده", severity: "high", category: "profanity" },
    { word: "کونی", severity: "high", category: "profanity" },
    { word: "کونی مقام", severity: "high", category: "profanity" },
    { word: "بچه کونی", severity: "high", category: "profanity" },
    { word: "بچه کیونی", severity: "high", category: "profanity" },
    { word: "کیونی", severity: "high", category: "profanity" },
    { word: "کونشو", severity: "high", category: "profanity" },
    { word: "کون گنده", severity: "high", category: "profanity" },
    { word: "سوراخ کون", severity: "high", category: "profanity" },
    { word: "سولاخ", severity: "high", category: "profanity" },
    { word: "باسن", severity: "high", category: "profanity" },
    { word: "پستان", severity: "high", category: "profanity" },
    { word: "پستون", severity: "high", category: "profanity" },
    { word: "پسون", severity: "high", category: "profanity" },
    { word: "آلت", severity: "high", category: "profanity" },
    { word: "آلت تناسلی", severity: "high", category: "profanity" },
    { word: "جنسی", severity: "high", category: "profanity" },
    { word: "دوجنسه", severity: "high", category: "profanity" },
    { word: "لاکونی", severity: "high", category: "profanity" },
    { word: "پشم کون", severity: "high", category: "profanity" },

    // === مشتقات خایه و ممه ===
    { word: "بی خایه", severity: "high", category: "profanity" },
    { word: "خایه مال", severity: "high", category: "profanity" },
    { word: "خایه خور", severity: "high", category: "profanity" },
    { word: "ممه خور", severity: "high", category: "profanity" },

    // === فحش‌های خوار و مادر و ترکیبات ناموسی شدید ===
    { word: "کسکش", severity: "high", category: "profanity" },
    { word: "کصکش", severity: "high", category: "profanity" },
    { word: "کس کش", severity: "high", category: "profanity" },
    { word: "جاکش", severity: "high", category: "profanity" },
    { word: "خارکسده", severity: "high", category: "profanity" },
    { word: "خارکس ده", severity: "high", category: "profanity" },
    { word: "خارکسّه", severity: "high", category: "profanity" },
    { word: "مادرجنده", severity: "high", category: "profanity" },
    { word: "مادر جنده", severity: "high", category: "profanity" },
    { word: "خواهرجنده", severity: "high", category: "profanity" },
    { word: "زن جنده", severity: "high", category: "profanity" },
    { word: "دخترجنده", severity: "high", category: "profanity" },
    { word: "کس ننت", severity: "high", category: "profanity" },
    { word: "مادرکونی", severity: "high", category: "profanity" },
    { word: "کصپدر", severity: "high", category: "profanity" },
    { word: "خار سولاخی", severity: "high", category: "profanity" },
    { word: "سولاخ مادر", severity: "high", category: "profanity" },
    { word: "خارتو", severity: "high", category: "profanity" },
    { word: "گی مادر", severity: "high", category: "profanity" },
    { word: "ننه هزار کیر", severity: "high", category: "profanity" },
    { word: "مادر فاکر", severity: "high", category: "profanity" },
    { word: "دول nنه", severity: "high", category: "profanity" },
    { word: "عمتو", severity: "high", category: "profanity" },
    { word: "عمه ننه", severity: "high", category: "profanity" },
    { word: "زنتو", severity: "high", category: "profanity" },
    { word: "زنشو", severity: "high", category: "profanity" },
    { word: "زنا", severity: "high", category: "profanity" },
    { word: "ظنا", severity: "high", category: "profanity" },
    { word: "زنازاده", severity: "high", category: "profanity" },
    { word: "ولدزنا", severity: "high", category: "profanity" },
  ],
};
