import { Dictionary } from "@textguard/core";

export const faSpam: Dictionary = {
    name: "fa-spam",
    language: "fa",
    version: "1.0.0",
    words: [
        // === شبکه های اجتماعی و ربات‌ها (حفاظت شده) ===
        { word: "خرید فالوور", severity: "high", category: "spam" },
        { word: "فالوور رایگان", severity: "high", category: "spam" },
        { word: "لایک تضمینی", severity: "medium", category: "spam" },
        { word: "سین تلگرام", severity: "medium", category: "spam" },
        { word: "فروش پیج", severity: "high", category: "spam" },
        { word: "فالو کن فالو بک", severity: "medium", category: "spam" },
        { word: "فالو=فالو", severity: "medium", category: "spam" },

        // === سیستم‌های پانزی، کریپتو زرد و کلاهبرداری (حفاظت شده) ===
        { word: "درآمد دلاری تضمینی", severity: "high", category: "spam" },
        { word: "پولدار شدن سریع", severity: "high", category: "spam" },
        { word: "استخراج بیت کوین در خانه", severity: "high", category: "spam" },
        { word: "سیگنال فیوچرز", severity: "high", category: "spam" },
        { word: "ربات ترید", severity: "high", category: "spam" },
        { word: "سرمایه‌گذاری با سود ثابت", severity: "high", category: "spam" },
        { word: "ارز دیجیتال رایگان", severity: "medium", category: "spam" },

        // === قمار، شرط بندی و تبلیغات زرد (حفاظت شده) ===
        { word: "پیش‌بینی فوتبال", severity: "high", category: "spam" },
        { word: "سایت شرط بندی", severity: "high", category: "spam" },
        { word: "انفجار بدون باخت", severity: "high", category: "spam" },
        { word: "کازینو آنلاین", severity: "high", category: "spam" },
        { word: "شارژ رایگان ایرانسل", severity: "high", category: "spam" },
        { word: "اینترنت رایگان واقعی", severity: "medium", category: "spam" },
        { word: "کلیک کن پول بگیر", severity: "high", category: "spam" },
        { word: "کار در منزل با حقوق بالا", severity: "medium", category: "spam" },

        // === فضولات و کثیف‌کاری‌های کلامی (اضافه شده از لیست جدید) ===
        { word: "گوه", severity: "high", category: "spam" },
        { word: "گه", severity: "high", category: "spam" },
        { word: "گهی", severity: "high", category: "spam" },
        { word: "عن", severity: "high", category: "spam" },
        { word: "انی", severity: "high", category: "spam" },
        { word: "عن دونی", severity: "high", category: "spam" },
        { word: "چس", severity: "medium", category: "spam" },
        { word: "چسو", severity: "medium", category: "spam" },
        { word: "چوسو", severity: "medium", category: "spam" },
        { word: "گوز", severity: "medium", category: "spam" },
        { word: "گوزو", severity: "medium", category: "spam" },
        { word: "گنده گوز", severity: "high", category: "spam" },
        { word: "چس خور", severity: "high", category: "spam" },
        { word: "چس خوری", severity: "high", category: "spam" },
        { word: "زارت", severity: "low", category: "spam" },
        { word: "شاش", severity: "high", category: "spam" },
        { word: "شاش خالی", severity: "high", category: "spam" },
        { word: "شاش خالی", severity: "high", category: "spam" },
        { word: "شاش بند", severity: "high", category: "spam" },
        { word: "ریدن", severity: "high", category: "spam" },
        { word: "ریدی", severity: "high", category: "spam" },
        { word: "ریدم", severity: "high", category: "spam" },
        { word: "لجن", severity: "medium", category: "spam" },
        { word: "کثافت", severity: "medium", category: "spam" },
        { word: "نکبت", severity: "medium", category: "spam" },

        // === چت‌رومی زرد، دوستیابی و ترولینگ (اضافه شده از لیست جدید) ===
        { word: "داف", severity: "medium", category: "spam" },
        { word: "داف ناز", severity: "medium", category: "spam" },
        { word: "دخترقرتی", severity: "medium", category: "spam" },
        { word: "قرتی", severity: "low", category: "spam" },
        { word: "دوست دختر", severity: "medium", category: "spam" },
        { word: "دوست پسر", severity: "medium", category: "spam" },
        { word: "سکس چت", severity: "high", category: "spam" },
        { word: "ماچ", severity: "low", category: "spam" },
        { word: "ماچ کردنی", severity: "low", category: "spam" },
        { word: "لاس", severity: "medium", category: "spam" },
        { word: "جوون", severity: "low", category: "spam" },
        { word: "هیز", severity: "medium", category: "spam" },
        { word: "خز", severity: "low", category: "spam" },
        { word: "نفس", severity: "low", category: "spam" },
        { word: "نعشه", severity: "high", category: "spam" },
        { word: "مشروب", severity: "high", category: "spam" },
        { word: "عرق خور", severity: "high", category: "spam" },
        { word: "زاخار", severity: "low", category: "spam" },
        { word: "خپل", severity: "low", category: "spam" }
    ],
};